[package]
name = "rust-net-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
# cs50 ai told me to use all of these
pnet = "0.34.0"
dns-lookup = "2.0.4"
reqwest = "0.12.22"
tokio = { version = "1", features = ["full"] }